channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
 - python>=3.5
 - scikit-learn>=0.20
 - matplotlib>=2.0
 - seaborn>=0.8
 - hdbscan=0.8.28
 - joblib>=1.0
 - cython>=0.27
 - numpy>=1.20
 - scipy>= 1.0

